<div dir = 'rtl'>
<h1>
למה פייתון?
</h1>
אנחנו משתמשים בפייתון כי זו שפה המאפשרת לממש קוד מתוך מאמרים מחקריים בצורה קצרה, תמציתית וקרובה מאד למקור.
בדף זה נראה כמה דוגמאות.
</div>

## 1. max

<div dir="rtl">
נניח שאנחנו רואים באלגוריתם מסוים את השורה הבאה, כאשר X היא קבוצה כלשהי של מספרים:
</div>

$$
z := \max_{x \in X, x \text{ is odd}} (x^2 - x)
$$

<div dir = 'rtl'>
איך היינו כותבים את זה בJava?
</div>

```Java
/* Java Code generated by Microsoft Copilot */

import java.util.Set;

public class MaxExpression {
    
    public static void main(String[] args) {
        Set<Double> X = Set.of(1.0, 2.0, 3.0); // Replace with actual values
        double z = maxExpression(X);
        System.out.println("The maximum value of the expression is: " + z);
    }

    public static double maxExpression(Set<Double> X) {
        double maxVal = Double.NEGATIVE_INFINITY;
        for (double x : X) {
            if (x%2 == 1) {      // if x is odd:
                double expressionValue = Math.pow(x, 2) - x;
                if (expressionValue > maxVal) {
                    maxVal = expressionValue;
                }
            }
        }
        return maxVal;
    }
}
```

<div dir = 'rtl'>
בפייתון נכתוב אותו הדבר בשורה אחת:
</div>

In [2]:
X = [1,2,3]

max(x**2-x for x in X if x%2==1)

6

## 2. arg max

<div dir='rtl'>
דוגמה נוספת:
</div>

$$
z := \arg \max_{x \in X, x \text{ is odd}} (x^2 - x)
$$

```Java
/* Java Code generated by Microsoft Copilot */

import java.util.Set;

public class MaxOddValue {
    public static void main(String[] args) {
        int[] X = {1, 2, 3, 4, 5, 6, 7}; // Example array X (you can replace with your own values)

        int maxOddValue = Integer.MIN_VALUE; // Initialize with smallest possible value
        int z = 0; // Initialize the result variable

        for (int x : X) {
            if (x % 2 == 1) { // Check if x is odd
                int currentValue = x * x - x;
                if (currentValue > maxOddValue) {
                    maxOddValue = currentValue;
                    z = x;
                }
            }
        }

        System.out.println("Maximum value occurs at x = " + z);
        System.out.println("Maximum value is " + maxOddValue);
    }
}
```

In [ ]:
X = [1,2,3,4,5]

max([x for x in X if x%2==1],  key=lambda x:x**2-x)

5

## 3. Swap

How do you swap two numbers? Three lines in Java:

```Java
public class Swapper {
    public static void main(String[] args) {
        int a=5, b=10;

        int temp = a; 
        a = b; 
        b = temp
}
```

One line in Python:

In [20]:
a,b = 5,10
print (a,b)

a,b = b,a
print (a,b)

5 10
10 5

You can even swap more than two numbers:

In [21]:
a,b,c = 5,10,15
print (a,b,c)

a,b,c = c,b,a
print (a,b,c)

5 10 15
15 10 5

## 4. Formatted strings

In [ ]:
f"a={a}, b={b:.2f}, c={c:.4f}"

'a=10, b=5.00, c=5.0000'

## 5. if-then-else

```Java
/* In Java: */

int x=99;
String s = (x > 10? "BIG": "SMALL");
```

In [3]:
x=99
s = "BIG" if x>10 else "SMALL"
print(s)

BIG

## map

Write a function that takes as input a string containing a list of integers separated by spaces, such as "11 22 33", and returns an array of these integers, e.g. [11,22,33].

```Java
    /* Java Code generated by Microsoft Copilot */

    public static int[] convertStringToIntArray(String str) {
        return Arrays.stream(str.split("\\s+")).mapToInt(Integer::parseInt).toArray();
    }
```

In [35]:
input = "11 22 33"
numbers_array = list(map(int, input.split()))
print(numbers_array)

[11, 22, 33]

Now, write a line that also squares each of these numbers and combines them back into a single string.

In [36]:
" ".join([str(int(x)**2) for x in input.split()])

'121 484 1089'

## Sort

You have a map from each person name to their age.
How do you get a list of all names, from youngest to oldest?

In [5]:
map_name_to_age = {"a": 50, "b": 55, "c": 45, "d": 38, "e": 72, "f":66}

# Short:
print(sorted(map_name_to_age.keys(), key=lambda name: map_name_to_age[name]))

# Shorter:
print(sorted(map_name_to_age.keys(), key=map_name_to_age.__getitem__))

['d', 'c', 'a', 'b', 'f', 'e']
['d', 'c', 'a', 'b', 'f', 'e']